### ISSUE TITLE
Make TradeOffer class exportable

### ISSUE THREAD

**Issue by serge1peshcoff** [DoctorMcKay/node-steam-tradeoffer-manager#226] opened 2017-05-16 09:41 UTC
I've recently stumbled upon the Bluebird library and its' [Promise.promisifyAll method](http://bluebirdjs.com/docs/api/promise.promisifyall.html).

It would be cool to have the ability to run 
```
Promise.promisifyAll(require('path-to-trade-offer-manager-class.js'))
Promise.promisifyAll(require('path-to-trade-offer-class.js'))
```
(or something like that, I didn't try it yet)

I know I can `require('steam-tradeoffer-manager/lib/index.js')` to get the `TradeOfferManager` class, but if I'll do `require('steam-tradeoffer-manager/lib/classes/TradeOffer.js')`, it will return an empty object, since this file doesn't export anything.

So it would be nice to make `lib/classes/TradeOffer.js` export the `TradeOffer` function, so I can `require` just this class and do stuff with it.

**Comment by serge1peshcoff** [comment] 2017-05-16 09:51
I'll most likely make a PR on this later when I'll play with it. I also want to refactor it a little bit.

For instance, I want to make `TradeOffer` and `TradeOfferManager` not dependent on each other, so I could use the one without the other (for now I can't). Also what I'd like to do is to move all `TradeOfferManager` functions out of` TradeOffer.js` to `index.js` (IMO the class functions should be located inside this class file). 

This would make the codebase much more readable.
@DoctorMcKay what do you think of that? I'd love to start working on it, but I need your opinion on that, what do you think of it and would you accept it if I'll make a PR.

**Comment by autaut03** [comment] 2017-05-16 12:51
It'd better to write a new library, imo.

**Comment by serge1peshcoff** [comment] 2017-05-16 12:55
@autaut03 I disagree, why writing a new library/creating a fork of the existing library if we can improve the existing one?
Heavy related xkcd: https://xkcd.com/927/

**Comment by autaut03** [comment] 2017-05-16 13:05
Because:
1) It's really slow. There's bunch of useless http request, and each request to steam takes over a second.
2) Events are sync.
3) The code is poor: no promises, no architecture, no code style, no es6. Just random pieces of really bad code.
4) Unmodifiable. It's really hard to understand the code and modify it, even if you fork.
5) There's a lot of useless functionality, such as dealing with real time trades, while no required functions, such as repeating accept/cancel/send, dealing with 28 error when accepting, no queues for accepting/canceling/sending, no ability to send items using not only assetid, but also classid/market_hash_name, so you have to write all those on your own.

This library may only work if you accept donations, and even then it works bad (if accept fails - it will never be called again). It is NOT a library, but a poorly written HTTP gate.

**Comment by serge1peshcoff** [comment] 2017-05-16 13:27
I agree with most of the things you said:
1. Didn't look into that in details, but probably you're right.
2. Totally agree (see my issue about promisifying requests in this repo).
3.  
  - Promises: see 2).
  - ES6:  I'd add the ES6 syntax if I was the maintainer though, it looks more clear. Though if some ES6 features would be added, it won't work with older Node versions (AFAIK Node v4 doesn't support classes, correct me if I'm wrong).
  - Code style: this should be fixable by adding the ESLint config and rewriting all `.js` files to match it.
  - Architecture: I agree that there are things that aren't clear, but what I'd proposed to change should make it better.
4. Here I have to disagree. I guess this library can be improved (again see the changes I've proposed)
5. Again agree, though I didn't look into it in details.

The thing is this library is one of the most downloaded Steam-related libraries, there's no real alternatives (correct me if I'm wrong). There are a lot of other people already using it (see https://www.npmjs.com/search?q=steam&page=1&ranking=popularity). IMO it would be better to improve this library (and I believe that it can be improved) than creating a new one/forking and rewriting this one.

Though if my changes won't be accepted, I'm going to fork and rewrite it, at least for myself.

**Comment by autaut03** [comment] 2017-05-16 13:37
3. Supporting node v4 is NOT required for a couple of reasons: 
1) it's not hyper-stable library that is used world-wide
2) node can only be installed on private server, not on hosting.
3) node v4 is already deprecated
The best choice is v6, if not v7.

If you agree with 1 and 5, then you cant disagree with 4 ;) To fix 1, 2, 3 and 5 - you are not only required to add some pieces of code, but to rewrite almost everything and develop almost everything from zero.
Believe me, I tried. I've used this library as base in one of my projects and to make it work I had to make a lot of changes in the library and use crutches in bot's code.

Also, some time ago I've suggested modifying some parts here, in github, and they were either ignored or declined.

**Comment by serge1peshcoff** [comment] 2017-05-16 13:53
@autaut03 I agree with what you're saying about supporting older Node versions.

For me in this case it's easier to edit the existing library than creating the new one from scratch. Because, to be honest, I have no idea how Steam API works, I've never worked with it before. And this repo for me is a base from which I can start exploring. It would be pain to implement all of this from scratch, I guess.

I've looked into NPM to find any alternatives to this lib, and it seems that there are almost none. For tradeoffers, there are 2 of them (that are frequently used): this one (the most downloaded) and `steam-tradeoffers` (I personally don't like that one, and also this lib is downloaded 2 times more daily). So there are 3 options for me:
1) editing this library by sending a PR
2) editing this library by forking it and using my fork in my project
3) inventing a wheel and making everything from scratch

Option 3) would take too much time, so I think it'll depend on @DoctorMcKay's opinion. If this issue would be ignored/rejected (and it probably will, since my other issue about promisifying is already open and inactive for half a year), I'll go with the option 2), I think.

**Comment by autaut03** [comment] 2017-05-16 14:01
@serge1peshcoff Okay, I understand your point. That's totally fine 👍

**Comment by Magalon** [comment] 2017-05-16 16:33
Guys, why won't you just team up together to make your own repo. Both of you can learn the Steam API together and try to make this world a better world! 

In a meantime, most of the dev here agree that McKay work is currently a complete repo out here for the Steam API. He open to suggestion but he, not a fool... He won't do all the work so you guys can have some easy solution in your hand. 

So you better start working your ass on that new library and see you in 2-3 years!

**Comment by serge1peshcoff** [comment] 2017-05-16 17:08
@Magalon please note that I didn't say something like "hey, this lib is a mess, please improve it". I said in my 1st comment to this issue that I'd love to make a PR on the changes I proposed. I just need the maintainer's opinion on that matter, so I would decide if I should make the PR on this repository or fork this library and adapt it for myself/anyone that would like to use it.

**Comment by Magalon** [comment] 2017-05-16 17:15
You didn't say it. but @autaut03 did 

> The code is poor: no promises, no architecture, no code style, no es6. Just random pieces of really bad code.

@serge1peshcoff why don't you just start it without is approval? Are you always asking your mom or dad permission each time you want to do something in the house? I don't think so... If you start it probably that more people may help in the process. But we don't have the time to do it as we speak...

**Comment by Magalon** [comment] 2017-05-16 18:21
It's far from an issue @serge1peshcoff don't you think?

**Comment by serge1peshcoff** [comment] 2017-05-16 18:25
@Magalon that's what I proposed at the first place (see my 1st comment to this issue).
I want to change way more than that, but I don't want to make one big pull request, it would be difficult to review (been there, done that).

Feel free to comment on this btw.

**Comment by DoctorMcKay** [comment] 2017-05-16 18:40
@autaut03:

1. I'm incredibly sorry that Steam is slow for you. I would fix that, but last I checked, I don't work for Valve.
2. Umm, yes? That's how node's EventEmitter works.
3. Promises aren't everything. Node itself doesn't use promises in its core library, which is why I haven't prioritized using them here. I don't use ES6 here because I want to support node v4 (which you say is unnecessary, but it is an LTS version). If the code is so bad, why don't you fix it and send pull requests?
4. You probably think it's unmodifiable because according to your GitHub profile, you tried to modify it to be a poller for the steamstat.us API. I have no idea why you thought it would be a good idea to rip the polling code out of a completely unrelated and relatively complex project when it's very easy to write on your own.
5. "Because I don't personally use it, x functionality is useless." People do use the real-time trading stuff. If you need to be able to add items by something other than their assetid, [Array.prototype.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) may be useful.

@serge1peshcoff I would kind of rather just add promise support manually than use Bluebird, which seems like more of a hack to me. I haven't reviewed your pull request yet, but I will check it later today. If you've done it in a good way then I may be willing to accept it instead of preferring to add promise support manually.

**Comment by serge1peshcoff** [comment] 2017-05-16 18:46
@DoctorMcKay I didn't add the Promise support yet, I want to finish the refactoring first.
And also I don't know a way to implement Promise support without making breaking changes, that's why I wanted to use Bluebird.
Anyway AFAIK it's faster than native Promise implementation and we can just do `Promise.promisifyAll` inside the library to add an async version of all methods, it's like 2 lines of code.

**Comment by DoctorMcKay** [comment] 2017-05-17 02:59
The non-breaking way I usually see of adding promise support is to check if a callback is provided and if not, return a promise.

**Comment by DoctorMcKay** [comment] 2017-05-17 03:11
This should be resolved by #227. Thanks.

**Closed by DoctorMcKay** 2017-05-17 03:11 UTC

**Comment by autaut03** [comment] 2017-05-17 21:37
@Magalon I did. 

@DoctorMcKay 
1. your library is slow, not steam. Lot's of USELESS request are made from your library that are not required.
2. So you just give up? Find another way then. The easiest that takes 1 minute - use async event emitter library.
3. You just skipped my arguments here.
4. Yep, I did it two years ago. My knowledge of JS was almost 0 at that time.
5. Again there, you skipped almost everything. Also array.filter doesn't do this: http://prntscr.com/f91vh1
Just a little part ONLY PREPARING to fetch inventories, find items and etc.

Deprecated code, useless extra requests, little functionallity. Those are ISSUES, BUGS. Aren't they supposed to be fixed by author?

**Comment by DoctorMcKay** [comment] 2017-05-17 22:02
Which requests, specifically, are not required?

Do you really understand what an "async event" is? All events in node execute synchronously. There is no benefit to making them async and in fact I don't believe it's possible without horrible hacks. The JavaScript portion of node is single-threaded. That's by design.

You seem to be overcomplicating Array.prototype.filter.

Are you back to saying that features existing which you don't personally use equate to a bug?

**Comment by autaut03** [comment] 2017-05-17 22:22
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L521
The most common example.

Tell this to https://www.npmjs.com/package/async-eventemitter
Also, I've said "the easiest solution". There are better ones, of course.

You seem to be repeating the same things twice, skipping everything I write.

Let real time trades be. I DID NOT notice them in my last message. Also, in my original message, I wrote that there are NO REQUIRED WHILE there are useless. It means that "useless" wasn't the point of that sentence.

Again, instead of doing extremely simple stuff (making to-do list on main page, fixing existing bugs, editing some parts) you keep repeating same things not even reading mine. 

That's ABANDONED project.

**Comment by Aareksio** [comment] 2017-05-17 23:07
@autaut03
We're happy you want to become a part of this open source project and already came with the list of things that are bad/broken in the library. Can't wait to see more of your contributions. Please make sure you follow the [contribution guide](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/CONTRIBUTING.md) while submiting your PR. Here's a [nodejs maintenance chart](https://github.com/nodejs/LTS) that may be useful to check which node versions are **not** depricated and should still be supported, please keep them in mind.

I see you have a problem with adding items to trade, filtered by other things than `assetid`, here is a little snippet you may be interested to use:

```JS
const selectedItems = items.filter(item => item.market_name === 'My Item Name');
offer.addItems(selectedItems);
```

Also, I'll just leave [this]( https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L507), [this](https://www.glassesusa.com/) and perhaps [this](https://nodesource.com/blog/understanding-the-nodejs-event-loop/) here for you.

**Comment by DoctorMcKay** [comment] 2017-05-18 02:46
async-eventemitter isn't emitting events asynchronously. It's just blocking further event listeners from being involved until previous ones indicate that they're done. There's no need for this in this project.

**Comment by scholtzm** [comment] 2017-05-18 05:46
> That's ABANDONED project.

I have dropped this module from my project and started rewriting everything from scratch after this comment. Thank you for letting us know.
