### ISSUE TITLE
Sentofferchanged is not always fired properly.

### ISSUE THREAD

**Issue by TheW1Red** [DoctorMcKay/node-steam-tradeoffer-manager#135] opened 2016-04-22 19:24 UTC
As the title suggests, Only a small percentage of the trades that change their state are being fired.
I've tried about 10 trades, where 3 of them didn't fire the event. All these trades were made exactly the same, so that shouldn't be the issue. 

To explain the log, It's making a trade and logging the item id, when the sentOfferChanged event is fired the "Sent offer changed (3)" message will apear. the number equals the state. As can be seen in the picture, I made two trades, but only 1 of them fired the sentOfferChanged event.

Your help would be appreciated.

![consolelog](https://cloud.githubusercontent.com/assets/18285144/14752523/00f27f72-08d0-11e6-9a87-7c9790971796.png)

**Comment by DoctorMcKay** [comment] 2016-04-22 20:50
Duplicate of #115 

Please post all information you have (version, logs, code) there.

**Closed by DoctorMcKay** 2016-04-22 20:50 UTC
Labels: duplicate
