### ISSUE TITLE
newOffer not coming in?

### ISSUE THREAD

**Issue by MordorKing78** [DoctorMcKay/node-steam-tradeoffer-manager#246] opened 2017-09-10 15:39 UTC
I'm trying to accept any offer from a Steam64ID but newOffer doesn't seem to be launched in any way..

Code:
```
const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');

const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager({
	steam: client,
	community: community,
	language: 'en'
});

const logOnOptions = {
	accountName: 'x',
	password: 'x$$',
	twoFactorCode: SteamTotp.generateAuthCode('x=')
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');

	client.setPersona(SteamUser.Steam.EPersonaState.Online);
	client.gamesPlayed(440);
});

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);

	community.setCookies(cookies);
	community.startConfirmationChecker(10000, 'x=');
});

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === '76561198368818576') {
		offer.accept((err, status) => {
			if (err) {
				console.log(err);
			} else {
				console.log(`Accepted offer. Status: ${status}.`);
			}
		});
	} else {
		offer.decline((err) => {
			if (err) {
				console.log(err);
			} else {
				console.log('Canceled offer from scammer.');
			}
		});
	}
});
```

**Comment by andrewda** [comment] 2017-09-10 16:41
This is certainly not a bug with `node-steam-tradeoffer-manager`, so this should probably be closed in favor of https://github.com/andrewda/node-steam-guide/issues/45.

**Comment by MordorKing78** [comment] 2017-09-10 17:46
@andrewda I mean isn't this the npm responsible for newOffer?

**Comment by andrewda** [comment] 2017-09-10 18:02
This module is responsible for emitting the `newOffer` event, but the module is working as expected (I just tried it out). Chances are something on your end isn't right (e.g. the trade offer wasn't sent, or wasn't sent at the right time).

**Comment by MordorKing78** [comment] 2017-09-10 18:20
@andrewda I tried multiple times after the message that the steam bot was logged in appeared, nothing else happens.

**Closed** 2017-09-12 17:40 UTC
Labels: question
