### ISSUE TITLE
'sentOfferChanged' doesn't call on csgo items

### ISSUE THREAD

**Issue by nhatkun** [DoctorMcKay/node-steam-tradeoffer-manager#353] opened 2024-04-07 13:31 UTC
'sentOfferChanged' doesn't call on csgo offer.
I tested that when decline/accept offer of csgo items, the event is not called.
I tested other game, all good.
So I try to found a solution to replace it by checking offer status continuously (manager.getOffer), but error show up "Access is denied".

ps: sorry for my bad english.

**Comment by DoctorMcKay** [comment] 2024-04-07 13:46
Duplicate of #348

**Closed by DoctorMcKay** 2024-04-07 13:46 UTC
